name: plankton
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - jupyter
      - pandas
      - ipykernel
      - scikit-image
      - scikit-learn
      - scikit-learn-intelex
      - ipykernel
      - matplotlib
      - shap
      - xgboost
